Standard search operator
subugoe/typo3-find pull request #166
Opened 2022-01-17 08:48 UTC by chrizzor

This PR adds the possiblity to configure the standard search operator. (e.g. mainQueryOperator = AND)

2022-01-17 13:41 UTC, ipf requested changes

2022-01-17 13:41 UTC, ipf commented on Classes/Service/SolrServiceProvider.php
> +        $this->addMainQueryOperator();
The naming of "MainQuery" is quite misleading here - I guess "DefaultQuery" is what expresses the method best

2022-01-17 13:41 UTC, ipf commented on Classes/Service/SolrServiceProvider.php
> +        $mainQueryOperator = 'AND';
This introduces a previously only implicit set operator `AND`. Why not leave this untouched and only do something in the `if`-clause below?

2022-01-17 13:41 UTC, ipf commented on Classes/Service/SolrServiceProvider.php
> +            $mainQueryOperator = $this->settings['mainQueryOperator'];
How should a developer know about this setting? It's not documented anywhere.
So, please put this in the documentation as well, and maybe provide examples in the TypoScript code.
Do we have to evaluate/trim the setting or silently fail if the operator is not supported by Solr (e.g `FOO` as setting)?

2022-01-17 13:42 UTC, ipf commented
Hi and thanks a lot for the PR.
I added a review.
Please provide an english commit message.

2022-05-19 13:43 UTC, mh-goe commented
Seems good to me. Thx for the contribution, @chrizzor

2022-05-19 13:43 UTC, merged