Add facet option (solr missing)
subugoe/typo3-find pull request #167
Opened 2022-01-17 08:57 UTC by chrizzor

This PR extends the facet configuration.
With "showmissing = 1" it is now possible to show all matching documents with no facet value.
The label for this facet option can be configured with "labelmissing".

2022-01-17 14:36 UTC, ipf requested changes

2022-01-17 14:36 UTC, ipf commented on Classes/Service/SolrServiceProvider.php
> +                    if ($facetTerm == $facetInfo['config']['labelmissing']) {
1. Please add the documentation / example for this parameter
2. For this parameter, please use a camelCasedVersion - `labelMissing`
3. Please use strict comparison `===`

2022-01-17 14:36 UTC, ipf commented on Classes/Service/SolrServiceProvider.php
> +                    if ($facet['showmissing'] == 1) {
Please use strict comparison. I know, the code part above does not use it, but we're about to change the strictness of the extension.

2022-05-20 07:20 UTC, ipf commented
Please rebase, fix the style with `composer lint` and check, why there are new indents in the Readme.

2022-05-20 07:20 UTC, ipf commented
Please rebase, fix the style with `composer lint` and check, why there are new indents in the Readme.

2022-09-05 15:45 UTC, chrizzor commented
Rebased and styling fixed

2022-09-12 08:10 UTC, merged